# Generated by Django 2.0.6 on 2019-12-16 16:53

from django.db import migrations
import projectApp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=projectApp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=projectApp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
